{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyundai-logger.fullname" . }}
  labels:
    {{- include "hyundai-logger.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.config.username | quote }}
  password: {{ .Values.config.password | quote }}
  pin: {{ .Values.config.pin | quote }}
{{- end }}
---
{{- if and (not .Values.influxdb.existingSecret) (not .Values.influxdb.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-influxdb" (include "hyundai-logger.fullname" .) }}
  labels:
    {{- include "hyundai-logger.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.influxdb.token | quote }}
{{- end }}
